[build-system]
requires = [
    "maturin>=1.10.2,<2.0",
]
build-backend = "maturin"


[project]
name = "mqt-naviz"
description = "A Visualizer for Neutral Atom Quantum Computers"
readme = "README.md"
authors = [
    { name = "Nico Petzendorfer", email = "nico.petzendorfer@tum.de" },
    { name = "Yannick Stade", email = "yannick.stade@tum.de" },
    { name = "Daniel Haag", email = "daniel.haag@tum.de" },
]
keywords = ["MQT", "quantum-computing", "design-automation", "compiler", "visualization", "neutral-atoms"]
license = "MIT"
license-files = ["python/LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
    "Topic :: Scientific/Engineering :: Quantum Computing",
    "Typing :: Typed",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/munich-quantum-toolkit/naviz"
Documentation = "https://mqt.readthedocs.io/projects/naviz"
Issues = "https://github.com/munich-quantum-toolkit/naviz/issues"
Discussions = "https://github.com/munich-quantum-toolkit/naviz/discussions"


[tool.maturin]
features = ["pyo3/extension-module"]
manifest-path = "bindings/Cargo.toml"
python-source = "python"
module-name = "mqt.naviz.pynaviz"
sdist-generator = "git"
exclude = [
    "docs/**/*",
    "test/python/**/*",
]

[tool.check-sdist]
git-only = [
    "docs/*",
    "test/python/*",
]


[tool.pytest]
minversion = "9.0"
testpaths = ["test/python"]
strict = true
addopts = [
    "-ra",
    "--showlocals",
]
log_level = "INFO"
filterwarnings = ["error"]


[tool.ruff]
line-length = 120
namespace-packages = ["mqt"]
preview = true
fix = true
unsafe-fixes = true
show-fixes = true
src = ["python"]

[tool.ruff.format]
preview = true
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "C90",     # <...> too complex
    "CPY001",  # Missing copyright notice at top of file
    "PLR09",   # Too many <...>
    "PLR2004", # Magic value used in comparison
    "S101",    # Use of assert detected
    "S404",    # `subprocess` module is possibly insecure
    "TID252"   # Prefer absolute imports over relative imports from parent modules
]
future-annotations = true

[tool.ruff.lint.isort]
known-first-party = ["mqt.naviz"]

[tool.ruff.lint.per-file-ignores]
"*.pyi" = ["D418", "E501", "PYI021", "PYI011"]
"docs/**" = ["INP001"]
"test/python/**" = ["INP001"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.ty.terminal]
# Error if ty emits any warning-level diagnostics.
error-on-warning = true

[tool.ty.src]
exclude = [
    "docs/**",
]


[tool.uv]
required-version = ">=0.5.20"
reinstall-package = ["mqt-naviz"]

[tool.uv.sources]
mqt-naviz = { workspace = true }


[tool.typos]
default.extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",  # ignore line
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on" # ignore block
]

[tool.typos.default.extend-words]
wille = "wille"
anc = "anc"
mch = "mch"
ket = "ket"


[tool.repo-review.ignore]
GH200 = "We use Renovate instead of Dependabot"
PC160 = "We use a mirror of crate-ci/typos"
PC170 = "We do not use rST files anymore"


[dependency-groups]
build = [
    "maturin>=1.10.2,<2.0",
]
test = [
    "pytest>=9.0.1",
]
docs = [
    "furo>=2025.09.25",
    "ipywidgets>=8.1.7",
    "myst-nb>=1.3.0",
    "sphinx>=8.2.3",
    "sphinx-autoapi>=3.6.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.6.1",
    "sphinx-llm>=0.4.1",
    "sphinxcontrib-rust>=1.0.0",
    "sphinxext-opengraph>=0.13.0",
]
dev = [
    {include-group = "build"},
    {include-group = "test"},
    "nox>=2025.11.12",
]
