name: Publish Crates

# This workflow publishes all crates in this repository

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CACHE_KEY: publish

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest
    environment: crates.io
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        with:
          cache-key: ${{ env.CACHE_KEY }}
      - name: Install Tools
        run: cargo install cargo-workspaces
      - name: Authenticate using Trusted Publishing
        uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
        id: auth
      - name: Publish Crates
        env:
          TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo ws publish --token "$TOKEN" --publish-as-is --skip-published
