name: Templating
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: read-release-drafter-categories
        run: |
          JSON_CONTENT=$(cat .github/workflow_inputs/release_drafter_categories.json | jq -c .)
          echo "release_drafter_categories=$JSON_CONTENT" >> $GITHUB_OUTPUT
      - id: create-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: munich-quantum-toolkit/templates@58aa931467691cea6d910016e1c75ab83780bc54 # v1.2.0
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: NAViz
          organization: ${{ github.repository_owner }}
          project-type: other
          repository: ${{ github.event.repository.name }}
          has-changelog-and-upgrade-guide: false
          synchronize-contribution-guide: false
          synchronize-installation-guide: false
          release-drafter-categories: ${{ steps.read-release-drafter-categories.outputs.release_drafter_categories }}
