name: Templating
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: read-release-drafter-categories
        run: |
          JSON_CONTENT=$(cat .github/workflow_inputs/release_drafter_categories.json | jq -c .)
          echo "release_drafter_categories=$JSON_CONTENT" >> $GITHUB_OUTPUT
      - id: create-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: munich-quantum-toolkit/templates@6b796f4c0404f74be469f32a3dcac05ef61d7b72 # v1.3.3
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: NAViz
          organization: ${{ github.repository_owner }}
          project-type: other
          repository: ${{ github.event.repository.name }}
          has-changelog-and-upgrade-guide: false
          synchronize-contribution-guide: false
          synchronize-installation-guide: false
          release-drafter-categories: ${{ steps.read-release-drafter-categories.outputs.release_drafter_categories }}
